export const DESKTOP = 'desktop'
export const MOBILE = 'mobile'
export const TABLET = 'tablet'
export const WEBSITE = 'Legal Checkup'

// Identifiers for testing
export const btnYes = 'btnYes'
export const btnNo = 'btnNo'
export const btnNotSure = 'btnNotSure'
export const progressBarId = 'progressBarId'
export const currentTopicId = 'currentTopicId'
export const counter = 'counter'
export const box = 'box'
export const exampleText = 'exampleText'
export const internalLink = 'internalLink'
export const externalLink = 'externalLink'
export const placeholder = 'placeholder'
export const responsive = 'responsive'
export const expanderText = 'expanderText'
export const allGoodText = 'allGoodText'
export const needHelpParagraph1 = 'needHelpParagraph1'
export const needHelpParagraph2 = 'needHelpParagraph2'
export const needHelpExpander = 'needHelpExpander'
export const redoBtn = 'redoBtn'
